- README.md
- package-lock.json
- package.json
Versions of non-development deps are now temporarily freezed.
> Freeze runtime dependencies

- src/index.ts
I hereby agree to the terms of the CLA available at: [[https://yandex.ru/legal/cla/?lang=en]. ](https://yandex.ru/legal/cla/?lang=en)
> fix: add ChartKitOnError type export

- src/components/ChartKit.scss
- src/components/ChartKit.tsx
- src/types/index.ts
This reverts commit 7ec399aec75c17165b029a9397b73404794c045b.
> Revert "add isMobile property (#55)"

- src/components/ChartKit.tsx
- src/plugins/highcharts/__stories__/Line.stories.tsx
- src/plugins/highcharts/renderer/HighchartsWidget.tsx
- src/plugins/highcharts/renderer/components/HighchartsComponent.tsx
- src/plugins/highcharts/types/index.ts
- src/plugins/highcharts/types/lib.ts
- src/plugins/highcharts/types/widget.ts
- src/plugins/index.ts
- src/types/widget.ts
- added property `hoistConfigError`
- added providing of `onError` props to chart component
- fixed highcharts reflow
> fix(Highcharts plaugin): fix error handling and reflow method

- src/components/ChartKit.tsx
Make id to be persistent on every render
> fix(ChartKit): id not to be new on every render

- src/plugins/highcharts/__stories__/Bar.stories.tsx
- src/plugins/highcharts/__stories__/Column.stories.tsx
- src/plugins/highcharts/__stories__/Pie.stories.tsx
- src/plugins/highcharts/__stories__/mocks/pie.ts
- src/plugins/highcharts/renderer/components/withSplitPane/withSplitPane.tsx
- src/plugins/highcharts/types/lib.ts
- src/plugins/highcharts/types/widget.ts
To avoid halo artifact like this:
<details>
<summary>Click</summary>
</details>
> fix(Highcharts plugin): fix pie halo on mobile devices

- src/plugins/highcharts/renderer/components/HighchartsComponent.tsx
Fix tooltip behaviour for onChartLoad & onRender callbacks
> fix(Highcharts plugin): fix tooltip behaviour

- src/plugins/highcharts/renderer/helpers/config/config.js
- src/plugins/highcharts/types/widget.ts
https://api.highcharts.com/highcharts/plotOptions.series.events.click
> feat(Highcharts plugin): add config.onSeriesClick property

- src/plugins/highcharts/renderer/helpers/tooltip/helpers.ts
> feat(Highcharts plugin)!: sort tooltip lines in desc order by default

- src/plugins/highcharts/renderer/helpers/config/config.js
- src/plugins/highcharts/renderer/helpers/config/utils/index.ts
- src/plugins/highcharts/renderer/helpers/tooltip/helpers.ts
- src/plugins/highcharts/renderer/helpers/tooltip/index.ts
- src/plugins/highcharts/renderer/helpers/tooltip/types.ts
- src/plugins/highcharts/types/widget.ts
> feat(Highcharts plugin)!: remove sort logic from tooltip to higher level

- package.json
> fix: remove sideEffects cause of it brokes styles

- package.json
Previous effort broke Storybook and was reverted
> feat: add `sideEffects`

- src/plugins/d3/renderer/D3Widget.tsx
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> fix(D3 plugin): fix resizing of several charts

- src/plugins/d3/__stories__/bar-x/СategoryAxis.stories.tsx
- src/plugins/d3/renderer/components/Chart.tsx
- src/plugins/d3/renderer/hooks/useShapes/bar-x.tsx
- src/plugins/d3/renderer/hooks/useShapes/defaults.ts
- src/plugins/d3/renderer/hooks/useShapes/index.tsx
- src/types/widget-data/series.ts
add [barMaxWidth](https://github.com/gravity-ui/chartkit/issues/275) and some other settings
Closes #275
> feat(D3 plugin): bar-x series options

- src/plugins/d3/renderer/D3Widget.tsx
- src/plugins/d3/renderer/components/Chart.tsx
- src/plugins/d3/renderer/components/Tooltip/TooltipTriggerArea.tsx
- src/plugins/d3/renderer/components/Tooltip/index.tsx
- src/plugins/d3/renderer/components/styles.scss
- src/plugins/d3/renderer/hooks/useShapes/index.tsx
- src/plugins/d3/renderer/hooks/useShapes/pie.tsx
- src/plugins/d3/renderer/hooks/useShapes/scatter/index.tsx
> refactor(D3 plugin): pointer position calculation fixes

- src/plugins/d3/__stories__/Showcase.stories.tsx
- src/plugins/d3/__stories__/bar-y/BarY.stories.tsx
- src/plugins/d3/__stories__/bar-y/Playground.stories.tsx
- src/plugins/d3/examples/bar-x/GroupedColumns.tsx
- src/plugins/d3/examples/bar-y/Basic.tsx
- src/plugins/d3/examples/bar-y/GroupedColumns.tsx
- src/plugins/d3/examples/bar-y/StackedColumns.tsx
- src/plugins/d3/renderer/components/Tooltip/DefaultContent.tsx
- src/plugins/d3/renderer/components/Tooltip/TooltipTriggerArea.tsx
- src/plugins/d3/renderer/constants/defaults/series-options.ts
- src/plugins/d3/renderer/hooks/useAxisScales/index.ts
- src/plugins/d3/renderer/hooks/useChartOptions/x-axis.ts
- src/plugins/d3/renderer/hooks/useChartOptions/y-axis.ts
- src/plugins/d3/renderer/hooks/useSeries/prepare-bar-x.ts
- src/plugins/d3/renderer/hooks/useSeries/prepare-bar-y.ts
- src/plugins/d3/renderer/hooks/useSeries/prepareSeries.ts
- src/plugins/d3/renderer/hooks/useSeries/types.ts
- src/plugins/d3/renderer/hooks/useShapes/bar-x/prepare-data.ts
- src/plugins/d3/renderer/hooks/useShapes/bar-y/index.tsx
- src/plugins/d3/renderer/hooks/useShapes/bar-y/prepare-data.ts
- src/plugins/d3/renderer/hooks/useShapes/bar-y/types.ts
- src/plugins/d3/renderer/hooks/useShapes/constants.ts
- src/plugins/d3/renderer/hooks/useShapes/index.tsx
- src/plugins/d3/renderer/hooks/useShapes/styles.scss
- src/plugins/d3/renderer/utils/axis-generators/bottom.ts
- src/plugins/d3/renderer/utils/text.ts
- src/types/widget-data/bar-y.ts
- src/types/widget-data/index.ts
- src/types/widget-data/series.ts
- src/types/widget-data/tooltip.ts
closed https://github.com/gravity-ui/chartkit/issues/315
> feat(D3 plugin): add base bar-y chart

- package-lock.json
- package.json
> fix: bumped yagr to 3.11.2 (fixed #344)

- src/components/ChartKit.scss
- src/plugins/d3/__stories__/Showcase.stories.tsx
- src/plugins/d3/__stories__/line/Playground.stories.tsx
- src/plugins/d3/examples/bar-x/DataLabels.tsx
- src/plugins/d3/examples/line/DataLabels.tsx
- src/plugins/d3/renderer/hooks/useChartOptions/y-axis.ts
- src/plugins/d3/renderer/hooks/useSeries/constants.ts
- src/plugins/d3/renderer/hooks/useSeries/prepare-bar-x.ts
- src/plugins/d3/renderer/hooks/useSeries/prepare-line-series.ts
- src/plugins/d3/renderer/hooks/useSeries/types.ts
- src/plugins/d3/renderer/hooks/useShapes/bar-x/index.tsx
- src/plugins/d3/renderer/hooks/useShapes/bar-x/prepare-data.ts
- src/plugins/d3/renderer/hooks/useShapes/bar-x/types.ts
- src/plugins/d3/renderer/hooks/useShapes/line/index.tsx
- src/plugins/d3/renderer/hooks/useShapes/line/prepare-data.ts
- src/plugins/d3/renderer/hooks/useShapes/line/types.ts
- src/plugins/d3/renderer/hooks/useShapes/utils.ts
- src/plugins/d3/renderer/types/index.ts
- src/plugins/d3/renderer/utils/__tests__/labels.test.ts
- src/plugins/d3/renderer/utils/index.ts
- src/plugins/d3/renderer/utils/labels.ts
- src/types/widget-data/base.ts
- src/types/widget-data/series.ts
closes https://github.com/gravity-ui/chartkit/issues/299
> feat(D3 plugin): add allowOverlap dataLabels option

- jest.config.ts
- src/plugins/d3/__stories__/Showcase.stories.tsx
- src/plugins/d3/examples/line/LineWithMarkers.tsx
- src/plugins/d3/renderer/hooks/useSeries/__tests__/prepare-line-series.test.ts
- src/plugins/d3/renderer/hooks/useSeries/prepare-line-series.ts
- src/plugins/d3/renderer/hooks/useSeries/types.ts
- src/plugins/d3/renderer/hooks/useShapes/line/index.tsx
- src/plugins/d3/renderer/hooks/useShapes/line/prepare-data.ts
- src/plugins/d3/renderer/hooks/useShapes/line/types.ts
- src/types/widget-data/line.ts
- src/types/widget-data/marker.ts
- src/types/widget-data/series.ts
closes https://github.com/gravity-ui/chartkit/issues/356
> feat(D3 plugin): marker for line charts

- src/plugins/highcharts/renderer/components/withSplitPane/withSplitPane.tsx
- src/plugins/indicator/__stories__/Indicator.stories.tsx
- src/plugins/indicator/renderer/IndicatorWidget.tsx
Fix lodash imports for better treeshaking
> fix: fix lodash imports

- src/plugins/d3/renderer/components/Tooltip/index.tsx
- src/plugins/d3/renderer/components/styles.scss
- src/plugins/d3/renderer/hooks/useSeries/prepare-pie.ts
- add `Popup` usage into `Tooltip`
- fix `pie` hover state
Closes https://github.com/gravity-ui/chartkit/issues/308
> refactor(D3 plugin): use Popup component for tooltip

- src/plugins/d3/__stories__/area/Playground.stories.tsx
- src/plugins/d3/__stories__/bar-x/Playground.stories.tsx
- src/plugins/d3/__stories__/bar-y/Playground.stories.tsx
- src/plugins/d3/__stories__/line/Playground.stories.tsx
- src/plugins/d3/__stories__/pie/Playground.stories.tsx
- src/plugins/d3/__stories__/scatter/Playground.stories.tsx
- src/plugins/d3/__stories__/treemap/Playground.stories.tsx
- src/plugins/d3/renderer/components/Chart.tsx
- src/plugins/d3/renderer/components/Tooltip/TooltipTriggerArea.tsx
- src/plugins/d3/renderer/d3-dispatcher.ts
- src/plugins/d3/renderer/hooks/useShapes/pie/index.tsx
- src/plugins/d3/renderer/hooks/useShapes/scatter/index.tsx
- src/plugins/d3/renderer/hooks/useShapes/treemap/index.tsx
- src/types/widget-data/chart.ts
> feat(D3 plugin): add chart click event

- src/plugins/d3/renderer/hooks/useSeries/prepare-line.ts
- src/plugins/d3/renderer/hooks/useSeries/prepare-pie.ts
- src/plugins/d3/renderer/hooks/useSeries/types.ts
- src/plugins/d3/renderer/hooks/useShapes/bar-x/index.tsx
- src/plugins/d3/renderer/hooks/useShapes/bar-x/prepare-data.ts
- src/plugins/d3/renderer/hooks/useShapes/bar-x/types.ts
- src/plugins/d3/renderer/hooks/useShapes/bar-y/index.tsx
- src/plugins/d3/renderer/hooks/useShapes/bar-y/prepare-data.ts
- src/plugins/d3/renderer/hooks/useShapes/bar-y/types.ts
- src/plugins/d3/renderer/hooks/useShapes/line/index.tsx
- src/plugins/d3/renderer/hooks/useShapes/line/prepare-data.ts
- src/plugins/d3/renderer/hooks/useShapes/line/types.ts
- src/plugins/d3/renderer/hooks/useShapes/marker.ts
- src/plugins/d3/renderer/hooks/useShapes/pie/index.tsx
- src/plugins/d3/renderer/hooks/useShapes/pie/prepare-data.ts
- src/plugins/d3/renderer/hooks/useShapes/pie/types.ts
- src/plugins/d3/renderer/hooks/useShapes/scatter/index.tsx
- src/plugins/d3/renderer/hooks/useShapes/scatter/prepare-data.ts
- src/plugins/d3/renderer/hooks/useShapes/scatter/types.ts
- src/types/widget-data/area.ts
- src/types/widget-data/bar-x.ts
- src/types/widget-data/bar-y.ts
- src/types/widget-data/line.ts
- src/types/widget-data/pie.ts
- src/types/widget-data/scatter.ts
* feat(D3 plugin): add opacity and marker setting to shape
* add jsdoc
> feat(D3 plugin): add opacity and marker setting to shape

- src/plugins/d3/__stories__/Showcase.stories.tsx
- src/plugins/d3/examples/area/NegativeValues.tsx
- src/plugins/d3/examples/bar-x/NegativeValues.tsx
- src/plugins/d3/examples/bar-y/NegativeValues.tsx
- src/plugins/d3/renderer/hooks/useAxisScales/index.ts
- src/plugins/d3/renderer/hooks/useChartOptions/y-axis.ts
- src/plugins/d3/renderer/hooks/useShapes/area/index.tsx
- src/plugins/d3/renderer/hooks/useShapes/area/prepare-data.ts
- src/plugins/d3/renderer/hooks/useShapes/bar-x/prepare-data.ts
- src/plugins/d3/renderer/hooks/useShapes/bar-y/prepare-data.ts
- src/plugins/d3/renderer/utils/index.ts
closes https://github.com/gravity-ui/chartkit/issues/393
> feat(D3 plugin): negative Y values for bar-x chart

- src/plugins/d3/__stories__/bar-y/Playground.stories.tsx
- src/plugins/d3/renderer/hooks/useAxisScales/index.ts
- src/plugins/d3/renderer/hooks/useChartOptions/x-axis.ts
- src/plugins/d3/renderer/hooks/useChartOptions/y-axis.ts
- src/plugins/d3/renderer/hooks/useSeries/prepare-bar-y.ts
- src/plugins/d3/renderer/hooks/useShapes/bar-y/prepare-data.ts
- src/plugins/d3/renderer/utils/axis-generators/bottom.ts
- src/plugins/d3/renderer/utils/index.ts
- src/types/widget-data/bar-y.ts
- fix `xAxis.lineColor` usage for the domain line
- correct minimum value for the X axis
- the `dataLabels.inside` cannot be set to false for percentage stack
> fix(D3 plugin): fix some errors in bar-y series

- src/plugins/d3/__stories__/line/Line.stories.tsx
- src/plugins/d3/examples/line/LogarithmicAxis.tsx
- src/plugins/d3/renderer/hooks/useAxisScales/index.ts
- src/plugins/d3/renderer/hooks/useChartOptions/y-axis.ts
- src/types/widget-data/axis.ts
closes https://github.com/gravity-ui/chartkit/issues/314
> feat(D3 plugin): add logarithmic type for x and y axes

- src/plugins/highcharts/renderer/helpers/highcharts/highcharts.js
<details>
<summary>Before:</summary>
https://github.com/user-attachments/assets/c38f7815-0b0d-43f3-b308-05e293e6ab28
</details>
<details>
<summary>After:</summary>
https://github.com/user-attachments/assets/94cac06a-54e1-4a51-9e15-a712ef8f588d
</details>
> fix(Highcharts plugin): fix tooltip hiding

- package-lock.json
- package.json
fix #500 in `@gravity-ui/yagr@4.3.3`
> fix: update yagr to v4.3.3

- src/plugins/highcharts/renderer/components/HighchartsComponent.tsx
> fix(Highcharts plugin): fix onRender invocation in case of splitted tooltip

- src/components/SplitPane/StyledSplitPane.scss
- src/plugins/d3/renderer/withSplitPane/withSplitPane.tsx
- src/plugins/highcharts/__stories__/column/VerticalStackedSplitTooltip.stories.tsx
- src/plugins/highcharts/__stories__/components/ChartStory.tsx
- src/plugins/highcharts/renderer/components/withSplitPane/withSplitPane.tsx
> fix: fix scroll in SplitPane
